# conda create -n iffont python=3.10
# conda env create -f environment.yaml

name: iffont
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10.12
  - pip=24.0
  - pytorch-cuda=11.8
  - pip:
    # torch: torch-2.2.1+cu118-cp310-cp310-linux_x86_64.whl
    - torch==2.2.1+cu118
    - torchvision==0.17.1+cu118
    - lightning==2.2.1
    - jsonargparse[signatures]==4.27.6
    - h5py==3.10.0
    - tqdm==4.66.2
    - matplotlib==3.8.3
    - omegaconf==2.3.0
    - tensorboardx==2.6.2.2
    - einops==0.7.0
    - transformers==4.38.2
    # for metrics in test
    - lpips==0.1.4
    - torch-fidelity==0.3.0
